{% set name = "fissix" %}
{% set version = "20.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ed6ca30ff516753eea3a6d337b1788327666c05ececedcff27a760dde5da576

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - appdirs
    - python

test:
  imports:
    - fissix
    - fissix.fixes
    - fissix.pgen2

about:
  home: https://github.com/jreese/fissix
  license: Python Software Foundation
  license_family: PSF
  license_file: LICENSE
  summary: Backport of lib2to3, with enhancements

extra:
  recipe-maintainers:
    - nicoddemus
