{% set name = "fissix" %}
{% set version = "21.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 756c47696a8d769ebf770ec7f018fd7b5948cd2cd6a204b5392bc9214ff795bc

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - appdirs
    - flit
    - pip
    - python >=3.6
  run:
    - appdirs
    - python >=3.6

test:
  imports:
    - fissix
    - fissix.fixes
    - fissix.pgen2

about:
  home: https://github.com/jreese/fissix
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Backport of lib2to3, with enhancements

extra:
  recipe-maintainers:
    - nicoddemus
