travis:
  secure:
    BINSTAR_TOKEN: Jc+C4WciR7b+c7aQQpWJU0kKaI5PFFdpSopX9b5PBjIqj8k2v1bVQV/TEEj5bjdioN7X6ndZeNhVSzNJ/iWv4TC3MFP+EbhxTO9Eo1TdzeVD/0bUCn/AgTqpbTPmtYhxxcC0I9X/GMSP1FRkZd4blb93qjwiq2a541C7TVyBZN1cv27S2d22XVbogZmCdSLDP3QxHTpTZqFHyGSDHYF+hAehYhW8Zowcm/06aC7336Co/XBlXSRLGqkReK8inGPSqT1TTeKCybs+XbNDeE1bj/4Q7rgAhZjDE/1Nwr5qmZneHr1OolE7huPg9mvXU35D7a8Gmyl8VypFVsTq38ruUGVAe23+RQvK8dDKdFoFGuw3Y6ppfM1YtsxKWN+oWESKP7KBcz+q3pbsHGCtV+d3kzSzXmwPtlSQfYrYINGaRyHm4WlNhV/WxPQM4dxNBW+5kuGz5UjpgInPGLsp8JuvBgUGnJJYmB0PZ+lTNtFv4dh8OiYOisjrVFQIfOQeLfFBDM36OSCWH7mfM+2szdJrEIrpyo5+USYlc2ttC1tx4wqorDb0GGIR07uwf94otLNQYpxAKuuOtxmqvzOkkAacBdWKC0ABvtRPtYP47r99n7R7eIiN8Cdl++PNB/R5AhQhiQhvavXjyKPvjqni0LTFYXIq2yaEeFKavGRW6xHQxjE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
